10. get articles by querying
zakaria552/News-API pull request #9
Opened 2022-11-16 11:56 UTC by zakaria552

2022-11-16 12:25 UTC, sirKevlar commented on __tests__/app.test.js
> +        })
We need one more happy path for if our client specifies an order in the query

2022-11-16 12:25 UTC, sirKevlar commented on __tests__/app.test.js
> +
We need one more sad path test for in any of the keys (sort|_by, order, topic) are misspelled

2022-11-17 09:15 UTC, callumu21 requested changes
Nice additions to the test suite. Just missing one more test - see my comments for advice.

2022-11-17 09:15 UTC, callumu21 commented on __tests__/app.test.js
> +        })
Just missing one test for a valid topic query that has no associated articles. What should be returned for a topic that exists in the database but has no articles? Currently, your code defaults to an error if the returned array is empty, but this isn't a bad request if the topic query exists in the database.

2022-11-17 10:13 UTC, Geo-Beard reviewed
Still need 2 more tests - see my comments.

2022-11-17 10:13 UTC, Geo-Beard commented on __tests__/app.test.js
> +    test("GET 200 - given no topic query returns all the articles", () => {
You still need a test for a valid topic that has no associated articles - i.e. valid topic, status 200, returns an empty array.

2022-11-17 10:13 UTC, Geo-Beard commented on __tests__/app.test.js
> +    })
Still need a test where /api/articles?order=asc or /api/articles?order=desc. Should be a status 200.

2022-11-17 10:24 UTC, closed without merging